export enum EmbedColors {
  GREEN = 3066993,
  PURPLE = 10181046,
  ORANGE = 15105570,
  RED = 15158332,
  NAVY = 3426654,
  DARK_PURPLE = 7419530,
}

export enum Notification {
  NONE = 'NONE',
  MEDIA_PENDING = 'MEDIA_PENDING',
  MEDIA_APPROVED = 'MEDIA_APPROVED',
  MEDIA_AVAILABLE = 'MEDIA_AVAILABLE',
  MEDIA_FAILED = 'MEDIA_FAILED',
  TEST_NOTIFICATION = 'TEST_NOTIFICATION',
  MEDIA_DECLINED = 'MEDIA_DECLINED',
  MEDIA_AUTO_APPROVED = 'MEDIA_AUTO_APPROVED',
  ISSUE_CREATED = 'ISSUE_CREATED',
  ISSUE_COMMENT = 'ISSUE_COMMENT',
  ISSUE_RESOLVED = 'ISSUE_RESOLVED',
  ISSUE_REOPENED = 'ISSUE_REOPENED',
  MEDIA_AUTO_REQUESTED = 'MEDIA_AUTO_REQUESTED',
}
